# GENERATED by scripts/generate_workspace_contracts.py; do not edit.
from __future__ import annotations
from typing import Literal, TypedDict, overload
import json
import math
from pathlib import Path
from jsonschema import Draft202012Validator, FormatChecker

class Money(TypedDict):
    currency: Literal['USD']
    microusd: int

class PinnedRefs(TypedDict):
    contract_version: Literal['workspace.v1']
    policy_version: Literal['P-01.v1']
    owner_id: str
    subject_id: str
    context_version_id: str
    workflow_id: str
    workflow_version_id: str

class ModelPin(TypedDict):
    provider: str
    model: str
    model_version: str
    data_route: str

class ModelOptionVariant0Capabilities(TypedDict):
    text: bool
    vision: bool
    tools: bool
    structured_output: bool

class ModelOptionVariant0(TypedDict):
    id: str
    pin: ModelPin
    availability: Literal['available']
    unavailable_reason: None
    capabilities: ModelOptionVariant0Capabilities
    allowed_tools: list[str]
    rate_card_version: str

class ModelOptionVariant1Capabilities(TypedDict):
    text: bool
    vision: bool
    tools: bool
    structured_output: bool

class ModelOptionVariant1(TypedDict):
    id: str
    pin: ModelPin
    availability: Literal['unavailable']
    unavailable_reason: str
    capabilities: ModelOptionVariant1Capabilities
    allowed_tools: list[str]
    rate_card_version: str | None

ModelOption = ModelOptionVariant0 | ModelOptionVariant1

class RateCardToolRatesItem(TypedDict):
    tool: str
    microusd_per_call: int

class RateCard(TypedDict):
    version: str
    model: ModelPin
    effective_at: str
    source_url: str
    verified_at: str
    currency: Literal['USD']
    input_microusd_per_million_tokens: int
    cache_read_microusd_per_million_tokens: int
    cache_write_microusd_per_million_tokens: int
    output_microusd_per_million_tokens: int
    tool_rates: list[RateCardToolRatesItem]
    retail_multiplier: Literal[3]

class Quote(TypedDict):
    id: str
    refs: PinnedRefs
    model: ModelPin
    rate_card_version: str
    input_fingerprint: str
    customer_max: Money
    upstream_max: Money
    created_at: str
    expires_at: str

class RunIntentConsent(TypedDict):
    model_data_route: Literal[True]
    customer_max: Literal[True]

class RunIntent(TypedDict):
    id: str
    quote: Quote
    idempotency_key: str
    requested_at: str
    consent: RunIntentConsent
    trigger: Literal['manual', 'schedule']
    schedule_id: str | None

class Reservation(TypedDict):
    id: str
    run_intent_id: str
    quote_id: str
    refs: PinnedRefs
    customer_reserved: Money
    upstream_reserved: Money
    status: Literal['held', 'settled', 'released', 'pending_reconciliation']
    created_at: str
    expires_at: str

class UsageReceiptVariant0(TypedDict):
    id: str
    run_intent_id: str
    reservation_id: str
    refs: PinnedRefs
    model: ModelPin
    rate_card_version: str
    measurement: Literal['actual']
    status: Literal['succeeded']
    input_tokens: int
    cache_read_tokens: int
    cache_write_tokens: int
    output_tokens: int
    tool_calls: int
    customer_charge: Money
    successful_path_upstream_cost: Money
    absorbed_retry_upstream_cost: Money
    total_upstream_cost: Money
    settled_at: str

class UsageReceiptVariant1CustomerCharge(TypedDict):
    currency: Literal['USD']
    microusd: Literal[0]

class UsageReceiptVariant1(TypedDict):
    id: str
    run_intent_id: str
    reservation_id: str
    refs: PinnedRefs
    model: ModelPin
    rate_card_version: str
    measurement: Literal['actual']
    status: Literal['failed']
    input_tokens: int
    cache_read_tokens: int
    cache_write_tokens: int
    output_tokens: int
    tool_calls: int
    customer_charge: UsageReceiptVariant1CustomerCharge
    successful_path_upstream_cost: Money
    absorbed_retry_upstream_cost: Money
    total_upstream_cost: Money
    settled_at: str

class UsageReceiptVariant2CustomerCharge(TypedDict):
    currency: Literal['USD']
    microusd: Literal[0]

class UsageReceiptVariant2(TypedDict):
    id: str
    run_intent_id: str
    reservation_id: str
    refs: PinnedRefs
    model: ModelPin
    rate_card_version: str
    measurement: Literal['estimated']
    status: Literal['pending_reconciliation']
    input_tokens: int | None
    cache_read_tokens: int | None
    cache_write_tokens: int | None
    output_tokens: int | None
    tool_calls: int | None
    customer_charge: UsageReceiptVariant2CustomerCharge
    successful_path_upstream_cost: Money | None
    absorbed_retry_upstream_cost: Money | None
    total_upstream_cost: Money | None
    settled_at: None

class UsageReceiptVariant3CustomerCharge(TypedDict):
    currency: Literal['USD']
    microusd: Literal[0]

class UsageReceiptVariant3(TypedDict):
    id: str
    run_intent_id: str
    reservation_id: str
    refs: PinnedRefs
    model: ModelPin
    rate_card_version: str
    measurement: Literal['unknown']
    status: Literal['pending_reconciliation']
    input_tokens: None
    cache_read_tokens: None
    cache_write_tokens: None
    output_tokens: None
    tool_calls: None
    customer_charge: UsageReceiptVariant3CustomerCharge
    successful_path_upstream_cost: None
    absorbed_retry_upstream_cost: None
    total_upstream_cost: None
    settled_at: None

UsageReceipt = UsageReceiptVariant0 | UsageReceiptVariant1 | UsageReceiptVariant2 | UsageReceiptVariant3

class WalletLot(TypedDict):
    id: str
    kind: Literal['included', 'purchased']
    granted: Money
    balance: Money
    reserved: Money
    consumed: Money
    granted_at: str
    expires_at: str
    stripe_source_id: str

class Wallet(TypedDict):
    owner_id: str
    policy_version: Literal['P-01.v1']
    currency: Literal['USD']
    stripe_subscription_id: str
    stripe_period_start: str
    stripe_period_end: str
    balance: Money
    reserved: Money
    consumed_this_cycle: Money
    purchased_this_cycle: Money
    upstream_exposure_this_cycle: Money
    lots: list[WalletLot]

class WorkspaceError(TypedDict):
    code: Literal['INVALID_CONTRACT', 'OWNER_SCOPE_MISMATCH', 'QUOTE_EXPIRED', 'QUOTE_MISMATCH', 'MODEL_UNAVAILABLE', 'RATE_CARD_UNAVAILABLE', 'INSUFFICIENT_BALANCE', 'RUN_RESERVATION_LIMIT', 'CYCLE_PURCHASE_LIMIT', 'CYCLE_CONSUMPTION_LIMIT', 'UPSTREAM_EXPOSURE_LIMIT', 'IDEMPOTENCY_CONFLICT', 'USAGE_PENDING_RECONCILIATION', 'ENROLLMENT_BLOCKED', 'LEGACY_ENTITLEMENT_REQUIRED']
    message: str
    retryable: bool
    request_id: str

_data = json.loads(Path(__file__).with_name("data.json").read_text())
contract_schema = _data["schema"]
policy = _data["policy"]
rate_cards = _data["rate_cards"]

@overload
def validate(name: Literal["Money"], value: object) -> Money: ...
@overload
def validate(name: Literal["PinnedRefs"], value: object) -> PinnedRefs: ...
@overload
def validate(name: Literal["ModelPin"], value: object) -> ModelPin: ...
@overload
def validate(name: Literal["ModelOption"], value: object) -> ModelOption: ...
@overload
def validate(name: Literal["RateCard"], value: object) -> RateCard: ...
@overload
def validate(name: Literal["Quote"], value: object) -> Quote: ...
@overload
def validate(name: Literal["RunIntent"], value: object) -> RunIntent: ...
@overload
def validate(name: Literal["Reservation"], value: object) -> Reservation: ...
@overload
def validate(name: Literal["UsageReceipt"], value: object) -> UsageReceipt: ...
@overload
def validate(name: Literal["WalletLot"], value: object) -> WalletLot: ...
@overload
def validate(name: Literal["Wallet"], value: object) -> Wallet: ...
@overload
def validate(name: Literal["WorkspaceError"], value: object) -> WorkspaceError: ...
def validate(name: str, value: object):
    """Validate without coercion; errors are stable at the API boundary."""
    if name not in contract_schema["$defs"]:
        raise ValueError("INVALID_CONTRACT: unknown contract")
    def finite_json(v):
        if isinstance(v, float) and not math.isfinite(v):
            raise ValueError("INVALID_CONTRACT: nonfinite number")
        if isinstance(v, dict):
            for key, item in v.items():
                if not isinstance(key, str):
                    raise ValueError("INVALID_CONTRACT: non-string object key")
                finite_json(item)
        elif isinstance(v, list):
            for item in v:
                finite_json(item)
    finite_json(value)
    from datetime import datetime
    checker = FormatChecker()
    @checker.checks("date-time", raises=ValueError)
    def valid_datetime(v):
        if not isinstance(v, str):
            return True
        datetime.fromisoformat(v.replace("Z", "+00:00"))
        return True
    validator = Draft202012Validator({"$ref": "#/$defs/" + name, "$defs": contract_schema["$defs"]}, format_checker=checker)
    errors = list(validator.iter_errors(value))
    if errors:
        raise ValueError("INVALID_CONTRACT: " + errors[0].message)
    return value
