#!/usr/bin/env python3
"""Offline deterministic workspace projections; validators are Zod/jsonschema.

This is deliberately NOT a JSON Schema compiler: the type-only projection supports
our closed wire vocabulary and fails on unrecognized type constructs. Runtime
semantics belong to maintained JSON Schema libraries, never this projection.
"""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'contracts/workspace-v1'


def type_of(s, language):
    if '$ref' in s:
        return s['$ref'].split('/')[-1]
    if 'anyOf' in s:
        return ' | '.join(type_of(x, language) for x in s['anyOf'])
    literals = s.get('enum', [s['const']] if 'const' in s else None)
    if literals is not None:
        if language == 'ts':
            return ' | '.join(json.dumps(x) for x in literals)
        return 'Literal[' + ', '.join(repr(x) for x in literals) + ']'
    kind = s['type']
    if kind == 'object':
        if s.get('additionalProperties') is not False or set(s['required']) != set(s['properties']):
            raise ValueError('Only closed, fully required wire objects supported')
        fields = [(k, type_of(v, language)) for k, v in s['properties'].items()]
        if language == 'ts':
            return '{ ' + '; '.join(json.dumps(k) + ': ' + v for k, v in fields) + ' }'
        # Nested TypedDicts are emitted separately; see python_types.
        raise ValueError('Nested object must have a named Python projection')
    if kind == 'array':
        t = type_of(s['items'], language)
        return f'Array<{t}>' if language == 'ts' else f'list[{t}]'
    return {'ts': {'string': 'string', 'integer': 'number', 'boolean': 'boolean', 'null': 'null'},
            'py': {'string': 'str', 'integer': 'int', 'boolean': 'bool', 'null': 'None'}}[language][kind]


def python_types(defs):
    lines = []
    def emit(name, schema):
        if 'anyOf' in schema:
            variants = []
            for i, variant in enumerate(schema['anyOf']):
                child = name + 'Variant' + str(i)
                emit(child, variant)
                variants.append(child)
            lines.append(name + ' = ' + ' | '.join(variants))
            return
        if schema.get('type') != 'object':
            lines.append(f'{name} = {type_of(schema, "py")}')
            return
        schema = json.loads(json.dumps(schema))
        def nested(s, prefix):
            if s.get('type') == 'object':
                emit(prefix, s)
                return {'$ref': '#/$defs/' + prefix}
            if s.get('type') == 'array':
                s['items'] = nested(s['items'], prefix + 'Item')
            if 'anyOf' in s:
                s['anyOf'] = [nested(x, prefix + str(i)) for i, x in enumerate(s['anyOf'])]
            return s
        fields = {k: nested(v, name + ''.join(p.title() for p in k.split('_'))) for k, v in schema['properties'].items()}
        lines.append('class ' + name + '(TypedDict):\n' + '\n'.join('    ' + k + ': ' + type_of(v, 'py') for k, v in fields.items()))
    for name, s in defs.items():
        emit(name, s)
    return '\n\n'.join(lines)


def outputs():
    schema = json.loads((SOURCE / 'schema.json').read_text())
    policy = json.loads((SOURCE / 'policy.p01.v1.json').read_text())
    rates = json.loads((SOURCE / 'rate-cards.json').read_text())
    payload = json.dumps(dict(schema=schema, policy=policy, rate_cards=rates), indent=2, ensure_ascii=True) + '\n'
    defs = schema['$defs']
    ts = '// GENERATED by scripts/generate_workspace_contracts.py; do not edit.\n'
    ts += 'import { fromJSONSchema } from "zod";\nimport data from "./data.json";\n'
    ts += '\n'.join(f'export type {n} = {type_of(s, "ts")};' for n, s in defs.items())
    ts += '\nexport type ContractMap = { ' + '; '.join(n + ': ' + n for n in defs) + ' };\n'
    ts += '''export const policy = data.policy;
export const rateCards: RateCard[] = data.rate_cards;
export const contractSchema = data.schema;
const validators = new Map<string, ReturnType<typeof fromJSONSchema>>();
export function validate<K extends keyof ContractMap>(name: K, value: unknown): ContractMap[K] {
  if (!Object.prototype.hasOwnProperty.call(data.schema.$defs, name)) throw new Error("INVALID_CONTRACT: unknown contract");
  let validator = validators.get(name);
  if (!validator) {
    validator = fromJSONSchema({ $ref: "#/$defs/" + name, $defs: data.schema.$defs } as Parameters<typeof fromJSONSchema>[0]);
    validators.set(name, validator);
  }
  return validator.parse(value) as ContractMap[K];
}
'''
    py = '# GENERATED by scripts/generate_workspace_contracts.py; do not edit.\nfrom __future__ import annotations\nfrom typing import Literal, TypedDict, overload\nimport json\nimport math\nfrom pathlib import Path\nfrom jsonschema import Draft202012Validator, FormatChecker\n\n'
    py += python_types(defs) + '\n\n'
    py += '_data = json.loads(Path(__file__).with_name("data.json").read_text())\ncontract_schema = _data["schema"]\npolicy = _data["policy"]\nrate_cards = _data["rate_cards"]\n\n'
    py += '\n'.join(f'@overload\ndef validate(name: Literal["{n}"], value: object) -> {n}: ...' for n in defs)
    py += '''
def validate(name: str, value: object):
    """Validate without coercion; errors are stable at the API boundary."""
    if name not in contract_schema["$defs"]:
        raise ValueError("INVALID_CONTRACT: unknown contract")
    def finite_json(v):
        if isinstance(v, float) and not math.isfinite(v):
            raise ValueError("INVALID_CONTRACT: nonfinite number")
        if isinstance(v, dict):
            for key, item in v.items():
                if not isinstance(key, str):
                    raise ValueError("INVALID_CONTRACT: non-string object key")
                finite_json(item)
        elif isinstance(v, list):
            for item in v:
                finite_json(item)
    finite_json(value)
    from datetime import datetime
    checker = FormatChecker()
    @checker.checks("date-time", raises=ValueError)
    def valid_datetime(v):
        if not isinstance(v, str):
            return True
        datetime.fromisoformat(v.replace("Z", "+00:00"))
        return True
    validator = Draft202012Validator({"$ref": "#/$defs/" + name, "$defs": contract_schema["$defs"]}, format_checker=checker)
    errors = list(validator.iter_errors(value))
    if errors:
        raise ValueError("INVALID_CONTRACT: " + errors[0].message)
    return value
'''
    web = ROOT / 'web/src/lib/workspace-contracts'
    worker = ROOT / 'worker/auditlayer_worker/workspace_contracts'
    return {web / 'index.ts': ts, web / 'data.json': payload,
            worker / '__init__.py': py, worker / 'data.json': payload}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    drift = []
    for path, content in outputs().items():
        if args.check:
            if not path.exists() or path.read_text() != content:
                drift.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if drift:
        print('Contract drift: ' + ', '.join(drift), file=sys.stderr)
        return 1
    print('workspace.v1: ' + ('projections match' if args.check else 'generated TS/Python projections'))
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
